---
- name: Configure Raspberry Pi servers
  hosts: servers
  become: true

  tasks:
    - name: Import essential configuration tasks
      ansible.builtin.import_tasks: tasks/essential.yml

  handlers:
    - name: Reload SSH
      ansible.builtin.service:
        name: ssh
        state: reloaded
